#!/bin/bash

exec >>/var/log/myvnc.log 2>&1

echo "$0: " "$@"

args=()
while [ "$#" -gt 0 ]; do
  arg="$1"
  case "$arg" in
    -screen)
      shift
      ;;
    *)
      args+=($arg)
      ;;
  esac
  shift
done

pid_to_kill=$PPID
Xvnc "${args[@]}" -geometry 1920x1080 -SecurityTypes none -inetd <&3 3>&-
kill -TERM "$pid_to_kill"
